# Generated by Django 2.2.1 on 2019-05-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageFileLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excelFile', models.FileField(upload_to='excelFile')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
